apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME
  annotations:
    cloud.google.com/backend-config: BACKEND_CONFIG_STRING
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: PORT_NUMBER
  selector:
    app: DEPLOYMENT_NAME