apiVersion: v1
kind: Service
metadata:
  name: auth-ms
  annotations:
    cloud.google.com/backend-config: '{"ports": {"http":"auth-ms"}}'
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: auth-ms